task4
arhab2001/Portfolio-HTML-Website pull request #4
Opened 2023-01-31 11:14 UTC by arhab2001

Contact left and right align issues

2023-01-31 13:31 UTC, Safnaj commented on index.html
> +        <p>Copyright Kevin. Made wtih <i class="fa-sharp fa-solid fa-heart"></i> by easy Tutorials</p>
remove Kevin and add your name

2023-01-31 13:32 UTC, Safnaj requested changes
Comments Added. Do the changes

2023-02-01 16:12 UTC, arhab2001 commented on index.html
> +        <p>Copyright Kevin. Made wtih <i class="fa-sharp fa-solid fa-heart"></i> by easy Tutorials</p>
ok

2023-02-01 17:57 UTC, Safnaj approved these changes

2023-02-01 17:57 UTC, merged